import Vue from "vue";
import 'element-ui/lib/theme-chalk/base.css';
import {
  Pagination,
  Avatar,
  Dialog,
  Autocomplete,
  Dropdown,
  DropdownMenu,
  DropdownItem,
  Menu,
  Submenu,
  MenuItem,
  MenuItemGroup,
  Input,
  InputNumber,
  Radio,
  RadioGroup,
  RadioButton,
  Checkbox,
  CheckboxButton,
  CheckboxGroup,
  Switch,
  Select,
  Option,
  OptionGroup,
  Button,
  ButtonGroup,
  Table,
  TableColumn,
  DatePicker,
  TimeSelect,
  TimePicker,
  Popover,
  Tooltip,
  Breadcrumb,
  BreadcrumbItem,
  Form,
  FormItem,
  Tabs,
  TabPane,
  Tag,
  Tree,
  Alert,
  Slider,
  Icon,
  Row,
  Col,
  Upload,
  Progress,
  Spinner,
  Badge,
  Card,
  Rate,
  Steps,
  Step,
  Carousel,
  CarouselItem,
  Collapse,
  CollapseItem,
  Cascader,
  ColorPicker,
  Container,
  Header,
  Aside,
  Main,
  Footer,
  Timeline,
  TimelineItem,
  Link,
  Divider,
  Image,
  Calendar,
  Backtop,
  PageHeader,
  CascaderPanel,
  Scrollbar,
  Transfer,
  Loading,
  MessageBox,
  Message,
  Notification,
  Popconfirm,
} from 'element-ui';
import CollapseTransition from 'element-ui/lib/transitions/collapse-transition';
const components = [
  Dialog,
  Avatar,
  Dropdown,
  DropdownMenu,
  DropdownItem,
  Menu,
  Submenu,
  MenuItem,
  Input,
  InputNumber,
  Checkbox,
  CheckboxGroup,
  Select,
  Option,
  Button,
  Breadcrumb,
  BreadcrumbItem,
  Form,
  FormItem,
  Table,
  TableColumn,
  Tree,
  Alert,
  Icon,
  Row,
  Col,
  Upload,
  Image,
  Scrollbar,
  Transfer,
  CollapseTransition,
  Pagination,
  Tag,

  Autocomplete,
  // MenuItemGroup,
  // Radio,
  // RadioGroup,
  // RadioButton,
  // CheckboxButton,
  Switch,
  // OptionGroup,
  // ButtonGroup,
  DatePicker,
  // TimeSelect,
  TimePicker,
  Popover,
  // Tooltip,
  // Tabs,
  // TabPane,
  // Slider,
  // Progress,
  // Spinner,
  // Badge,
  // Card,
  // Rate,
  // Steps,
  // Step,
  // Carousel,
  // CarouselItem,
  // Collapse,
  // CollapseItem,
  // Cascader,
  // ColorPicker,
  // Transfer,
  // Container,
  // Header,
  // Aside,
  // Main,
  // Footer,
  // Timeline,
  // TimelineItem,
  // Link,
  // Divider,
  // Calendar,
  // Backtop,
  // PageHeader,
  // CascaderPanel,
  Popconfirm,
];

Vue.use(Loading.directive);
components.forEach(component => {
  Vue.component(component.name, component)
})

Vue.prototype.$loading = Loading.service;
Vue.prototype.$msgbox = MessageBox;
Vue.prototype.$alert = MessageBox.alert;
Vue.prototype.$confirm = MessageBox.confirm;
Vue.prototype.$prompt = MessageBox.prompt;
Vue.prototype.$notify = Notification;
Vue.prototype.$message = Message;